import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building, ClipboardCheck, Compass, HardHat, Settings, Users } from "lucide-react";
import { PageShell } from "@/components/page-shell";
export const metadata: Metadata={title:"Services"};
const groups=[{icon:HardHat,n:"01",title:"Oil & Gas Construction",intro:"Construction support shaped around safety, quality, and the practical demands of energy-sector operations.",items:["Civil and structural works","Facility construction support","Mechanical and installation support","Maintenance and rehabilitation works"]},{icon:ClipboardCheck,n:"02",title:"Contract Services",intro:"Well-coordinated contract execution with clear responsibilities, reporting, and delivery controls.",items:["Project and service contracts","Procurement coordination","Subcontractor coordination","Quality and progress reporting"]},{icon:Compass,n:"03",title:"Consultancy",intro:"Practical commercial and project advice for organizations working across the oil and gas value chain.",items:["Project planning and advisory","Contract strategy support","Business and operational consulting","Local market and stakeholder insight"]}];
export default function Services(){return <PageShell>
  <section className="inner-hero services-hero"><div className="hero-grid"/><div className="container"><p className="eyebrow light">Our services</p><h1>Capability that moves<br/>projects forward.</h1></div></section>
  <section className="section"><div className="container split-intro"><div><p className="eyebrow">What we do</p><h2>Three connected service areas. One delivery mindset.</h2></div><div><p className="lead">We support clients from early planning through project execution, bringing together construction capability, contract coordination, and sector-focused consultancy.</p></div></div></section>
  <section className="service-bands">{groups.map(({icon:Icon,n,title,intro,items},i)=><article className={i%2?"service-band alt":"service-band"} key={title}><div className="container service-band-grid"><div className="service-icon"><Icon/></div><div><span className="service-number">{n}</span><h2>{title}</h2><p className="lead">{intro}</p></div><ul>{items.map(item=><li key={item}><ArrowRight/>{item}</li>)}</ul></div></article>)}</section>
  <section className="section pale"><div className="container"><div className="section-heading"><div><p className="eyebrow">How we support delivery</p><h2>Practical strength at every stage</h2></div></div><div className="feature-row"><article><Building/><h3>Local knowledge</h3><p>Understanding of the Niger Delta environment and Nigerian business context.</p></article><article><Settings/><h3>Coordinated execution</h3><p>Structured delivery, responsive communication, and attention to project controls.</p></article><article><Users/><h3>Client alignment</h3><p>Solutions shaped around the client's scope, priorities, and expected outcomes.</p></article></div></div></section>
  <section className="cta"><div className="container cta-inner"><div><p className="eyebrow">Discuss your requirements</p><h2>Need a reliable project partner?</h2></div><Link className="button button-dark" href="/contact">Request a consultation <ArrowRight size={18}/></Link></div></section>
 </PageShell>}
