import type { Metadata } from "next";
import { Mail, MapPin, Phone } from "lucide-react";
import { PageShell } from "@/components/page-shell";
export const metadata: Metadata={title:"Contact Us"};
export default function Contact(){return <PageShell>
  <section className="inner-hero contact-hero"><div className="hero-grid"/><div className="container"><p className="eyebrow light">Contact us</p><h1>Let's discuss what<br/>you need to deliver.</h1></div></section>
  <section className="section"><div className="container contact-intro"><div><p className="eyebrow">How can we help?</p><h2>Speak with Inemwills Enterprise.</h2></div><p className="lead">Tell us about your construction, contract, or consultancy requirement. Our team will review your enquiry and respond through the contact details you provide.</p></div></section>
  <section className="section pale"><div className="container contact-grid"><div className="contact-details"><p className="eyebrow">Our office</p><h2>Yenagoa, Bayelsa State</h2><div className="contact-item"><MapPin/><div><strong>Office address</strong><span>Bakery Road, Azikoro Town,<br/>Yenagoa, Bayelsa State, Nigeria.</span></div></div><div className="contact-item"><Phone/><div><strong>Call us</strong><a href="tel:+2347031216293">0703 121 6293</a><a href="tel:+2348083978685">0808 397 8685</a></div></div><div className="contact-item"><Mail/><div><strong>Email</strong><a href="mailto:info@inemwills.com">info@inemwills.com</a></div></div></div>
  <form className="contact-form" action="mailto:info@inemwills.com" method="post" encType="text/plain"><p className="eyebrow">Send an enquiry</p><h2>Tell us about your project</h2><label>Full name<input name="name" type="text" required placeholder="Your full name"/></label><div className="form-row"><label>Email address<input name="email" type="email" required placeholder="you@company.com"/></label><label>Phone number<input name="phone" type="tel" placeholder="Your phone number"/></label></div><label>Service needed<select name="service" defaultValue=""><option value="" disabled>Select a service</option><option>Oil & Gas Construction</option><option>Contract Services</option><option>Consultancy</option><option>General Enquiry</option></select></label><label>Message<textarea name="message" required rows={5} placeholder="Briefly describe your requirement"/></label><button className="button button-dark" type="submit">Send message</button></form></div></section>
 </PageShell>}
