import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Eye, Flag, Gem, Handshake, Leaf, ShieldCheck } from "lucide-react";
import { PageShell } from "@/components/page-shell";
export const metadata: Metadata={title:"About Us"};
const values=[{icon:ShieldCheck,title:"Integrity",text:"We act responsibly, communicate honestly, and remain accountable for our work."},{icon:Gem,title:"Excellence",text:"We pursue strong technical standards and disciplined execution on every engagement."},{icon:Handshake,title:"Partnership",text:"We build productive relationships with clients, contractors, communities, and stakeholders."},{icon:Leaf,title:"Sustainability",text:"We support safer, more efficient operations that respect people and the environment."}];
export default function About(){return <PageShell>
  <section className="inner-hero about-hero"><div className="hero-grid"/><div className="container"><p className="eyebrow light">Who we are</p><h1>Built on responsibility.<br/>Driven by results.</h1></div></section>
  <section className="section"><div className="container split-intro"><div><p className="eyebrow">About Inemwills</p><h2>A dependable partner for energy-sector projects.</h2></div><div><p className="lead">Inemwills Enterprise is a Nigerian company providing oil and gas construction, contract, and consultancy services. Based in Yenagoa, Bayelsa State, we help clients move from project intent to practical delivery.</p><p>Our approach combines local knowledge, responsive coordination, safety awareness, and a clear focus on value. We work to understand each assignment, align the right resources, and deliver solutions suited to the operating environment.</p></div></div></section>
  <section className="section pale"><div className="container vision-grid"><article><Eye/><p className="eyebrow">Our vision</p><h2>To be a trusted Nigerian partner for safe and effective oil and gas project delivery.</h2></article><article><Flag/><p className="eyebrow">Our mission</p><h2>To provide reliable construction, contract, and advisory solutions that create measurable value for every client.</h2></article></div></section>
  <section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Our values</p><h2>The principles behind our work</h2></div></div><div className="values-grid">{values.map(({icon:Icon,title,text})=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="section strategy"><div className="container strategy-grid"><div><p className="eyebrow light">Our approach</p><h2>From clear planning to controlled execution.</h2></div><ol><li><span>01</span><div><h3>Understand</h3><p>Clarify the scope, objectives, operating conditions, and stakeholder expectations.</p></div></li><li><span>02</span><div><h3>Plan</h3><p>Define a practical delivery path, responsibilities, resources, and controls.</p></div></li><li><span>03</span><div><h3>Deliver</h3><p>Execute with attention to safety, quality, communication, and accountability.</p></div></li></ol></div></section>
  <section className="cta"><div className="container cta-inner"><div><p className="eyebrow">Work with us</p><h2>Let's build value together.</h2></div><Link className="button button-dark" href="/contact">Contact Inemwills <ArrowRight size={18}/></Link></div></section>
 </PageShell>}
